# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: DirtyBit
subtitle:
author: Y2Nk4
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://dirtybit.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: DirtyBit | DirtyBit.me
header-img: images/header-tiny.jpg
email: me@y2nk4.com
description: ""
keyword: ""


# SNS settings
# RSS: false
weibo_username:
zhihu_username:
github_username:    Y2Nk4
twitter_username:
facebook_username:
linkedin_username:  gjiahao

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username: dirtybit-1

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id:
# Google Analytics
ga_track_id:            # Format: UA-xxxxxx-xx
ga_domain:


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "I am Y2Nk4 a UB CS undergrad student, check out my GitHub profile for details!"
sidebar-avatar:      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
friends: [
    {
        title: "Y2Nk4",
        href: "https://y2nk4.com"
    }
]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: i_dont_wanna_use_default_archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ZenMind

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/Y2Nk4/dirtybit.me
  branch: gh-pages
